### ISSUE TITLE
Implementing VrepVFController

### ISSUE THREAD

**Issue by ahundt** [jhu-saw/sawConstraintController#12]
I'm in the process of implementing the initial version of VrepVFController, which should perform basic inverse kinematics solving using mtsVFFollow.cpp.

My first problem was a crash on UpdateOptimizer() as follows:
I'm getting a crash from mtsVFFollow.cpp with the following stack trace:

```
#0	0x00007fff872ac286 in __pthread_kill ()
#1	0x00007fff8a6d842f in pthread_kill ()
#2	0x00007fff911b7b53 in abort ()
#3	0x00007fff8d310a21 in abort_message ()
#4	0x00007fff8d3389b9 in default_terminate_handler() ()
#5	0x00007fff87bfe7eb in _objc_terminate() ()
#6	0x00007fff8d3360a1 in std::__terminate(void (*)()) ()
#7	0x00007fff8d335b30 in __cxa_throw ()
#8	0x000000011933a4ce in void cmnThrow<std::runtime_error>(std::runtime_error const&, short) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstCommon/cmnThrow.h:93
#9	0x0000000119339f9b in vctDynamicVectorLoopEngines::ThrowException() at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstVector/vctDynamicVectorLoopEngines.h:73
#10	0x000000011941d26d in void vctDynamicVectorLoopEngines::VoVi<vctUnaryOperations<double, double>::Identity>::Run<vctDynamicVectorBase<vctDynamicVectorRefOwner<double>, double>, vctDynamicConstVectorRef<double> >(vctDynamicVectorBase<vctDynamicVectorRefOwner<double>, double>&, vctDynamicConstVectorRef<double> const&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstVector/vctDynamicVectorLoopEngines.h:562
#11	0x000000011937e420 in vctDynamicVectorBase<vctDynamicVectorRefOwner<double>, double>& vctDynamicVectorBase<vctDynamicVectorRefOwner<double>, double>::Assign<3ul, 1l, double, double [3]>(vctFixedSizeConstVectorBase<3ul, 1l, double, double [3]> const&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstVector/vctDynamicVectorBase.h:295
#12	0x000000011937e193 in mtsVFFollow::FillInTableauRefs(mtsVFBase::CONTROLLERMODE, double) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/sawConstraintController/code/mtsVFFollow.cpp:77
#13	0x000000011936fe06 in mtsVFController::UpdateOptimizer(double) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/sawConstraintController/code/mtsVFController.cpp:317
#14	0x00000001193269d0 in grl::VrepInverseKinematicsController::run_one() at /Users/athundt/source/robonetracker/modules/grl/include/grl/cisst/VrepVFController.hpp:265
#15	0x0000000119324a1b in v_repMessage at /Users/athundt/source/robonetracker/modules/grl/src/v_repExtGrlInverseKinematics/v_repExtGrlInverseKinematics.cpp:272
#16	0x0000000102ed0da9 in CPluginContainer::sendEventCallbackMessageToAllPlugins(int, int*, void*, int*) ()
#17	0x0000000102ec6f87 in _workThread(void*) ()
#18	0x0000000102b04646 in Thread::run() ()
#19	0x0000000100052e60 in ___lldb_unnamed_function350$$QtCore ()
#20	0x00007fff8a6d6268 in _pthread_body ()
#21	0x00007fff8a6d61e5 in _pthread_start ()
#22	0x00007fff8a6d441d in thread_start ()

```

In particular I've been able to verify that [mtsVFFollow.cpp line 77](https://github.com/jhu-saw/sawConstraintController/blob/92af15d6c0feb88642bae5a3a3b9a8606b799928/code/mtsVFFollow.cpp#L77) is being passed with the values in the following state. In particular you'll want to see dx_translation vector near the bottom:

```
this	mtsVFFollow *	0x10077f270	0x000000010077f270
mtsVFJointPosition	mtsVFJointPosition		
CurrentKinematics	prmKinematicsState *	0x104493b70	0x0000000104493b70
Frame	vctFrm3		
RotationMember	vctFrameBase<vctMatrixRotation3<double, true> >::RotationType		
vctMatrixRotation3Base<vctFixedSizeMatrix<double, 3, 3, true> >	vctMatrixRotation3Base<vctFixedSizeMatrix<double, 3, 3, true> >		
vctMatrixRotation3ConstBase<vctFixedSizeMatrix<double, 3, 3, true> >	vctMatrixRotation3ConstBase<vctFixedSizeMatrix<double, 3, 3, true> >		
vctFixedSizeMatrix<double, 3, 3, true>	vctFixedSizeMatrix<double, 3, 3, true>		
vctFixedSizeMatrixBase<3, 3, 3, 1, double, double [9]>	vctFixedSizeMatrixBase<3, 3, 3, 1, double, double [9]>		
vctFixedSizeConstMatrixBase<3, 3, 3, 1, double, double [9]>	vctFixedSizeConstMatrixBase<3, 3, 3, 1, double, double [9]>		
Data	vctFixedSizeConstMatrixBase<3, 3, 3, 1, double, double [9]>::DataType		
[0]	double	1	1
[1]	double	0	0
[2]	double	0	0
[3]	double	0	0
[4]	double	1	1
[5]	double	0	0
[6]	double	0	0
[7]	double	0	0
[8]	double	1	1
TranslationMember	vctFrameBase<vctMatrixRotation3<double, true> >::TranslationType		
vctFixedSizeVectorBase<3, 1, double, double [3]>	vctFixedSizeVectorBase<3, 1, double, double [3]>		
vctFixedSizeConstVectorBase<3, 1, double, double [3]>	vctFixedSizeConstVectorBase<3, 1, double, double [3]>		
Data	double [3]		
[0]	double	0	0
[1]	double	0	0
[2]	double	0	0
CartesianVelocity	vct3		
vctFixedSizeVectorBase<3, 1, double, double [3]>	vctFixedSizeVectorBase<3, 1, double, double [3]>		
AngularVelocity	vct3		
Jacobian	vctDoubleMat		
InverseJacobian	vctDoubleMat		
UserCount	int	0	0
Name	std::__1::string	"IK_Group1_iiwa"	
NeedsBase	bool	false	false
JointState	prmJointState *	NULL	0x0000000000000000
DesiredKinematics	prmKinematicsState *	0x104493df0	0x0000000104493df0
Frame	vctFrm3		
RotationMember	vctFrameBase<vctMatrixRotation3<double, true> >::RotationType		
vctMatrixRotation3Base<vctFixedSizeMatrix<double, 3, 3, true> >	vctMatrixRotation3Base<vctFixedSizeMatrix<double, 3, 3, true> >		
vctMatrixRotation3ConstBase<vctFixedSizeMatrix<double, 3, 3, true> >	vctMatrixRotation3ConstBase<vctFixedSizeMatrix<double, 3, 3, true> >		
vctFixedSizeMatrix<double, 3, 3, true>	vctFixedSizeMatrix<double, 3, 3, true>		
vctFixedSizeMatrixBase<3, 3, 3, 1, double, double [9]>	vctFixedSizeMatrixBase<3, 3, 3, 1, double, double [9]>		
vctFixedSizeConstMatrixBase<3, 3, 3, 1, double, double [9]>	vctFixedSizeConstMatrixBase<3, 3, 3, 1, double, double [9]>		
Data	vctFixedSizeConstMatrixBase<3, 3, 3, 1, double, double [9]>::DataType		
[0]	double	1	1
[1]	double	0	0
[2]	double	0	0
[3]	double	0	0
[4]	double	1	1
[5]	double	0	0
[6]	double	0	0
[7]	double	0	0
[8]	double	1	1
TranslationMember	vctFrameBase<vctMatrixRotation3<double, true> >::TranslationType		
vctFixedSizeVectorBase<3, 1, double, double [3]>	vctFixedSizeVectorBase<3, 1, double, double [3]>		
vctFixedSizeConstVectorBase<3, 1, double, double [3]>	vctFixedSizeConstVectorBase<3, 1, double, double [3]>		
Data	double [3]		
[0]	double	0.19874370098114014	0.19874370098114014
[1]	double	-0.74582469463348389	-0.74582469463348389
[2]	double	0.5781978964805603	0.5781978964805603
CartesianVelocity	vct3		
AngularVelocity	vct3		
Jacobian	vctDoubleMat		
InverseJacobian	vctDoubleMat		
UserCount	int	0	0
Name	std::__1::string	"RobotMillTipTarget"	
NeedsBase	bool	false	false
JointState	prmJointState *	NULL	0x0000000000000000
JacResized	vctDoubleMat		
dx_translation	vct3		
vctFixedSizeVectorBase<3, 1, double, double [3]>	vctFixedSizeVectorBase<3, 1, double, double [3]>		
vctFixedSizeConstVectorBase<3, 1, double, double [3]>	vctFixedSizeConstVectorBase<3, 1, double, double [3]>		
Data	double [3]		
[0]	double	0.19874370098114014	0.19874370098114014
[1]	double	-0.74582469463348389	-0.74582469463348389
[2]	double	0.5781978964805603	0.5781978964805603
```

**Comment by pkazanzides** [comment]
Can you take a look at the cisstLog.txt?  From the stack trace, it is clear that you got an exception from a cisst dynamic vector -- probably something like a size mismatch.  Further details will be in cisstLog.txt, as well as via `runtime_error::what()`, which you can print if you add a `try...catch` to your code (which will also prevent the crash).

**Comment by pwilken3** [comment]
It's likely that you're trying to assign data to the vector reference without allocating enough memory for it. The number of rows in the matrix reference and size of the vector reference depend on the number of rows you assign it in its data object. Otherwise mtsVFFollow should work, so I suspect this is the case.

**Comment by ahundt** [comment]
It seems that dx_translation is a vector containing 3 values and ObjectiveVectorRef contains 7 elements.

**Comment by ahundt** [comment]
I'm not sure where those values are being set and why, but it feels like a translation 3 vector may be inadvertently assigned to a joint angle 7 vector. Any thoughts?

Also why is JacResized setting column 6 specifically to 0, and resizing the jacobian to 3x7 in [mtsVFFollow.cpp line 67](https://github.com/jhu-saw/sawConstraintController/blob/92af15d6c0feb88642bae5a3a3b9a8606b799928/code/mtsVFFollow.cpp#L69)? That seems like it would be for a very specific arm, rather than generalized to work for any arm.

```c++
    vctDoubleMat JacResized = CurrentKinematics->Jacobian;
    JacResized.resize(3,7);
    JacResized.Column(6).SetAll(0.0);
```

**Comment by pwilken3** [comment]
You're right about the resizing of the jacobian, I can take that part out since it should just be whatever jacobian is passed in. The way you set the number of rows (at least for an objective VF) would be setting the value of mtsVFFollowData.ObjectiveRows to 3 when initializing.

**Comment by ahundt** [comment]
Ok that was my problem, I had set it to be equal to the number of joints, when it should really be a cartesian objective. I've now made it to the next problem which is in the call to `nmrConstraintOptimizer::Solve()`.

stack trace:
```
#0	0x0000123526adf933 in dgels_ ()
#1	0x0000123526a98ab7 in int nmrLSqLin<vctDynamicMatrixOwner<double>, vctDynamicVectorOwner<double> >(vctDynamicMatrixBase<vctDynamicMatrixOwner<double>, double>&, vctDynamicVectorBase<vctDynamicVectorOwner<double>, double>&, nmrLSqLinSolutionDynamic&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstNumerical/nmrLSqLin.h:1245
#2	0x0000123526a9707a in nmrConstraintOptimizer::Solve(vctDynamicVector<double>&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstNumerical/code/nmrConstraintOptimizer.cpp:73
#3	0x00001235269eeeaf in mtsVFController::Solve(vctDynamicVector<double>&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/sawConstraintController/code/mtsVFController.cpp:329
#4	0x00001235269a5abd in grl::VrepInverseKinematicsController::run_one() at /Users/athundt/source/robonetracker/modules/grl/include/grl/cisst/VrepVFController.hpp:271
#5	0x00001235269a3beb in v_repMessage at /Users/athundt/source/robonetracker/modules/grl/src/v_repExtGrlInverseKinematics/v_repExtGrlInverseKinematics.cpp:272
#6	0x0000000102c03da9 in CPluginContainer::sendEventCallbackMessageToAllPlugins(int, int*, void*, int*) ()
#7	0x0000000102bf9f87 in _workThread(void*) ()
#8	0x0000000102837646 in Thread::run() ()
#9	0x0000000100067e60 in ___lldb_unnamed_function350$$QtCore ()
#10	0x00007fff8a6d6268 in _pthread_body ()
#11	0x00007fff8a6d61e5 in _pthread_start ()
#12	0x00007fff8a6d441d in thread_start ()
```

of particular interest is the line it is failing on:
```
#if defined(CISSTNETLIB_VERSION_MAJOR)
#if (CISSTNETLIB_VERSION_MAJOR >= 3)
    cisstNetlib_dgels_(&trans, &rows, &cols, &nrhs,
                       A.Pointer(), &lda,
                       b.Pointer(), &maxmn,
                       solutionFriend.GetWork().Pointer(), &lwork, &ret_value);
#endif
#else // no major version
    dgels_(&trans, &rows, &cols, &nrhs, // <<<<<<<<<<<<<< fails here
           A.Pointer(), &lda,
           b.Pointer(), &maxmn,
           solutionFriend.GetWork().Pointer(), &lwork, &ret_value);
#endif // CISSTNETLIB_VERSION
```

Perhaps something special needs to be done to make sure the linear algebra pack is available? 

Also, perhaps it would be better if this code were calling what appears to be the newer `#if (CISSTNETLIB_VERSION_MAJOR >= 3)` statement?

It seems `nmrConfig.h ` has the following:

```
// Do we have cisstNetlib
#define CISST_HAS_CISSTNETLIB 1
```

But no definition of `CISSTNETLIB_VERSION_MAJOR`

**Comment by pwilken3** [comment]
You have cisstNetlib, correct? CISSTNETLIB_VERSION_MAJOR should be defined in cisstNetlib.h.

**Comment by pkazanzides** [comment]
The code wouldn't compile/link without cisstNetlib.  Clearly, Andrew has an older version, since CISSTNETLIB_VERSION_MAJOR is not defined.  As a minor point, I think it wold be better to change the conditional compilation, since the code will not handle any case where CISSTNETLIB_VERSION_MAJOR is defined, but less than 3 (even though this should never happen).

**Comment by ahundt** [comment]
This may be due to my cmake configuration if the CMake scripts in cisst make certain assumptions. If the version is defined via CMake in CISST, the CISST implementations may incorrectly assume that macro has been defined in every case where a cisst library is being included. If true that just means my use case where I add_subdirectory(cisst-saw) from my own build hasn't yet been accounted for in the CMake scripts.

**Comment by pkazanzides** [comment]
The version is not defined via the cisst CMake, but appears in cisstNetlib.h (only for version 3.0.0 and above).  If the version is not defined in cisstNetlib.h, it is an older version.

The cisstNetlib source code is on GitHub:  https://github.com/jhu-cisst/cisstNetlib.  It is possible to build from source, but mostly people use pre-built binaries.  Cisst contains a FindCisstNetlib.cmake module, which first looks for an existing cisstNetlib (e.g., in /usr or /usr/local).  If not found, it offers a CMake option to download the binary installation, which it gets from our server (http://unittest.lcsr.jhu.edu).

Do you recall whether you selected the CMake option to download cisstNetlib?

**Comment by ahundt** [comment]
Yes, from my CMakeCache.txt:

```cmake

//Path were cisstNetlib has been downloaded
CISSTNETLIB_DIR:PATH=/Users/athundt/source/robonetracker/xcodebuild/thirdparty/cisst-saw/cisst/cisstNumerical/cisstNetlib-2.0-MacOS-intel

//No help, variable specified on the command line.
CISSTNETLIB_DOWNLOAD_NOW:UNINITIALIZED=ON

//Path to a library.
CISSTNETLIB_G95_LIBRARY:FILEPATH=/Users/athundt/source/robonetracker/xcodebuild/thirdparty/cisst-saw/cisst/cisstNumerical/cisstNetlib-2.0-MacOS-intel/lib/libcisstNetlibgfortran.a

//Path to a library.
CISSTNETLIB_LIBRARY:FILEPATH=/Users/athundt/source/robonetracker/xcodebuild/thirdparty/cisst-saw/cisst/cisstNumerical/cisstNetlib-2.0-MacOS-intel/lib/libcisstNetlib.a
```

**Comment by ahundt** [comment]
Interesting, the path contains `/cisstNetlib-2.0-MacOS-intel`. Here is my header, looks like I do have 2.0. Perhaps a bug in the DOWNLOAD_NOW implementation?

```c
#ifndef _cisstNetlib_h
#define _cisstNetlib_h
#define CISSTNETLIB_VERSION 2 
#define CISSTNETLIB_SIZEOF_SHORT 2
#define CISSTNETLIB_SIZEOF_INT 4
#define CISSTNETLIB_SIZEOF_LONG 4
#define CISSTNETLIB_SIZEOF_LONG_LONG 8
#define CISSTNETLIB_SIZEOF_FLOAT 4
#define CISSTNETLIB_SIZEOF_DOUBLE 8
#define CISSTNETLIB_SIZEOF_LONG_DOUBLE 16
extern "C" {
  #include "cisstNetlib/lapack.h"
  #include "cisstNetlib/lawson-hanson.h"
  #include "cisstNetlib/minpack.h"
  #include "cisstNetlib/o8para.h"
  #include "cisstNetlib/o8userfunc.h"
  #include "cisstNetlib/hanson-haskell.h"
}
#endif
```

**Comment by ahundt** [comment]
I tried an alternate approach of adding the latest cisstNetlib as a subdirectory of my build tree. However it seems the libraries that build by default don't include a few required functions as detailed below:

```
Undefined symbols for architecture x86_64:
  "_dgelss_", referenced from:
      robManipulator::OSinertia(double (*) [6], vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
  "_dgemm_", referenced from:
      robManipulator::InverseKinematics(vctDynamicVector<double>&, vctFrame4x4<double, true> const&, double, unsigned long, double) in libcisstRobot.a(robManipulator.o)
      robManipulator::JacobianSpatial(vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
      robManipulator::OSinertia(double (*) [6], vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
  "_dgemv_", referenced from:
      robManipulator::InverseKinematics(vctDynamicVector<double>&, vctFrame4x4<double, true> const&, double, unsigned long, double) in libcisstRobot.a(robManipulator.o)
      robManipulator::InverseDynamics(vctDynamicVector<double> const&, vctDynamicVector<double> const&, vctFixedSizeVector<double, 6ul> const&) const in libcisstRobot.a(robManipulator.o)
  "_dgesv_", referenced from:
      robManipulator::InverseKinematics(vctDynamicVector<double>&, vctFrame4x4<double, true> const&, double, unsigned long, double) in libcisstRobot.a(robManipulator.o)
  "_dnrm2_", referenced from:
      robManipulator::InverseKinematics(vctDynamicVector<double>&, vctFrame4x4<double, true> const&, double, unsigned long, double) in libcisstRobot.a(robManipulator.o)
  "_dpotrf_", referenced from:
      robManipulator::OSinertia(double (*) [6], vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
  "_dpotri_", referenced from:
      robManipulator::OSinertia(double (*) [6], vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
  "_dsymm_", referenced from:
      robManipulator::OSinertia(double (*) [6], vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
  "_dsymv_", referenced from:
      robManipulator::InverseDynamics(vctDynamicVector<double> const&, vctDynamicVector<double> const&, vctFixedSizeVector<double, 6ul> const&) const in libcisstRobot.a(robManipulator.o)
      robManipulator::InverseDynamics(vctDynamicVector<double> const&, vctDynamicVector<double> const&, vctDynamicVector<double> const&) const in libcisstRobot.a(robManipulator.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any suggestions on how to get this configuration to be correct?

**Comment by ahundt** [comment]
I'm pretty stuck at this point and I'm not familiar with how to deal with this fortran stuff, so I'll need some assistance to keep moving forward on this.

**Comment by pkazanzides** [comment]
@ahundt, I think you are chasing a red herring here.  While it would be good to understand cisstNetlib a bit better, we started down this path because you noticed that `#if (CISSTNETLIB_VERSION_MAJOR >= 3)` is false in your configuration.  This led to the speculation that the problem was due to an outdated version of cisstNetlib.  I think that is unlikely.  My guess is that the same problem will occur with the latest version of cisstNetlib. So, we should go back to investigating the original problem, which appears to be some kind of exception or crash in the `dgels_` function, which is called by `nmrConstraintOptimizer::Solve` via `nmrLSqLin`.

@pwilken3: have you tested the constrained optimizer for the case where there is only an objective function and no constraints?

**Comment by pwilken3** [comment]
Yes, the optimizer is able to find solutions given no constraints.

**Comment by ahundt** [comment]
Those errors are just a simple linker error, I was only hoping for help finding out what package needs to be linked to fix it. 

I feel like going back to the beginning would take a bit more effort than adding one more linker flag, then even if it doesn't solve the original problem I'll have a more current version of the optimizer to use and won't have to deal with it in the future.

**Comment by ahundt** [comment]
Found a solution, cisstnetlib doesn't support being built as a subdirectory. Compiling and installing it then using the configure scripts it provides worked OK. On to the next step!

**Comment by ahundt** [comment]
You were right, I'm right back to the previous spot, but now in the other side of the new code side of `#if (CISSTNETLIB_VERSION_MAJOR >= 3)`. This looks like a sizing error for the dimensions of the data, which makes sense with `EXEC_BAD_ACCESS` errors.

Could you perhaps suggest assertions/preconditions I can add to narrow this down?

**Comment by ahundt** [comment]
I've gone through and done some detailed debugging of the current state, but I don't know enough about what the functions are trying to do to figure out the final fix/conclusion. I've got all the info below and would appreciate your thoughts!


Key Observations
------------------------

**The invalid memory address access occurred at:**
`EXEC_BAD_ACCESS (code=1,address=0x123c98d58000)`

**The first address of b.Vector.Data is**
`(value_type *) Data = 0x0000123c98d57fe0`

**b.Vector.Data is just below the bad access address, a 32 byte difference**

However, b.Vector.size is 3, and 3x8=24 bytes. It is either a problem with this data component, the relevant sizes, or whatever is right next to it in memory. Perhaps the function where it is crashing thinks b.vector.data is larger than it really is?



stack trace
---------------

```
#0	0x000012352503966a in dgels_ ()
#1	0x0000123525024fc9 in cisstNetlib_dgels_ ()
#2	0x0000123525151bd7 in int nmrLSqLin<vctDynamicMatrixOwner<double>, vctDynamicVectorOwner<double> >(vctDynamicMatrixBase<vctDynamicMatrixOwner<double>, double>&, vctDynamicVectorBase<vctDynamicVectorOwner<double>, double>&, nmrLSqLinSolutionDynamic&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstNumerical/nmrLSqLin.h:1239
#3	0x000012352515019a in nmrConstraintOptimizer::Solve(vctDynamicVector<double>&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/cisst/cisstNumerical/code/nmrConstraintOptimizer.cpp:73
#4	0x00001235250a7fcf in mtsVFController::Solve(vctDynamicVector<double>&) at /Users/athundt/source/robonetracker/thirdparty/cisst-saw/sawConstraintController/code/mtsVFController.cpp:329
#5	0x0000123524ff0b9d in grl::VrepInverseKinematicsController::run_one() at /Users/athundt/source/robonetracker/modules/grl/include/grl/cisst/VrepVFController.hpp:271
#6	0x0000123524feeccb in v_repMessage at /Users/athundt/source/robonetracker/modules/grl/src/v_repExtGrlInverseKinematics/v_repExtGrlInverseKinematics.cpp:272
#7	0x0000000102c03da9 in CPluginContainer::sendEventCallbackMessageToAllPlugins(int, int*, void*, int*) ()
#8	0x0000000102bf9f87 in _workThread(void*) ()
#9	0x0000000102837646 in Thread::run() ()
#10	0x0000000100067e60 in ___lldb_unnamed_function350$$QtCore ()
#11	0x00007fff8a6d6268 in _pthread_body ()
#12	0x00007fff8a6d61e5 in _pthread_start ()
#13	0x00007fff8a6d441d in thread_start ()
```

nmrLSqLin function signature
----------------------------------

code is # 2 in stack trace above, signature is at line 1193 of nmrLSqLin.h

```c++
/*! This function checks for valid input and
  calls the LAPACK function. The approach behind this defintion of the
  function is that the user creates a solution object from a code
  wherein it is safe to do memory allocation. This solution object
  is then passed on to this method along with the matrix whose
  LSqLin is to be computed. The solution object has members X
  and Work etc., which can be accessed through calls to method
  get*() along with adequate workspace for LAPACK.
  This function modifies the contents of matrix A.
  For details about nature of the solution matrices see text above.
  \param A A matrix of size MxN, of one of vctDynamicMatrix or vctDynamicMatrixRef
  \param b A vector of size N, of one of vctDynamicVector or vctDynamicVectorRef
  \param solution A solution object of one of the types corresponding to
  input matrix
  TESTS:
  nmrLSqLinSolverTest::TestDynamicColumnMajor
  nmrLSqLinSolverTest::TestDynamicRowMajor
  nmrLSqLinSolverTest::TestDynamicColumnMajorUserAlloc
  nmrLSqLinSolverTest::TestDynamicRowMajorUserAlloc
*/
template <typename _matrixOwnerType, typename _vectorOwnerType>
inline CISSTNETLIB_INTEGER nmrLSqLin(vctDynamicMatrixBase<_matrixOwnerType, CISSTNETLIB_DOUBLE> &A,
                          vctDynamicVectorBase<_vectorOwnerType, CISSTNETLIB_DOUBLE> &b,
                          nmrLSqLinSolutionDynamic &solution) throw (std::runtime_error)
```

Line  where invalid memory access occurs 
--------------------------------------------------------

is in `nmrLSqLin()` function call `line 1239 of nmrLSqLin.h`:
```c++
    cisstNetlib_dgels_(&trans, &rows, &cols, &nrhs,
                       A.Pointer(), &lda,
                       b.Pointer(), &maxmn,
                       solutionFriend.GetWork().Pointer(), &lwork, &ret_value);
```



Additional info just in case, but you can probably skip it
---------------------------------

The first address of A.Matrix.Data is
`(value_type *) Data = 0x0000123c98d55f50`
solutionFriend.solution.Work.Vector.Data:
```
(value_type *) Data = 0x0000123c98d63fd0 
```



A is a 7 row 3 column matrix in column major format with the following values:
```
*(double(*)[21])A.Matrix.Data	double [21]		
[0]	double	-0.99997121546261014
[1]	double	0.000014649223852906956
[2]	double	-0.98470096687206632
[3]	double	0.000027360892998320942
[4]	double	-1.0651805473988456
[5]	double	-0.0000086133235447094503
[6]	double	0.000019595544784911476
[7]	double	-0.27988579726076096
[8]	double	-0.18544759337289576	
[9]	double	-0.00001490030661835835
[10]	double	0.81621317634076485
[11]	double	0.070650264902564042
[12]	double	-0.000020115433578761876
[13]	double	-0.14414343287323547
[14]	double	0.85536944950188099
[15]	double	0.99991483949665915
[16]	double	-0.021966204455107108
[17]	double	-0.29002518525873711
[18]	double	0
[19]	double	0
[20]	double	0
```

B is a 3 element vector, where `b.size() == A.rows()`.
```
*(double(*) [3])b.Vector.Data	double [3]		
[0]	double	-0.19874942189130579
[1]	double	0.70018344301348456
[2]	double	-2.0625513253027012
```

The values of the remaining integer parameters are as follows:
```
ret_value	CISSTNETLIB_INTEGER	0	
rows	CISSTNETLIB_INTEGER	3	
cols	CISSTNETLIB_INTEGER	7	
trans	char	'N'	
nrhs	CISSTNETLIB_INTEGER	1	
lda	CISSTNETLIB_INTEGER	3	
maxmn	CISSTNETLIB_INTEGER	7	
lwork	CISSTNETLIB_INTEGER	6	
```


The elements in solutionFriend.GetWork.Pointer() I believe to be the following
`solution.work.Data`:
```
*(double(*) [6])solution.Work.Vector.Data	double [6]		
[0]	double	1.0000851632497196
[1]	double	1.1326311969047391
[2]	double	1.0984406210311812
[3]	double	3
[4]	double	1.0442057313405226
[5]	double	0
```

`solutionFriend.solution.Work.Vector.data`:
```
*(double(*)[6])solutionFriend.solution.Work.Vector.Data	double [6]		
[0]	double	1.0000851632497196	1.0000851632497196
[1]	double	1.1326311969047391	1.1326311969047391
[2]	double	1.0984406210311812	1.0984406210311812
[3]	double	3	3
[4]	double	1.0442057313405226	1.0442057313405226
[5]	double	0	0
```

**Comment by ahundt** [comment]
I also found some [documentation of dgels in netlib](http://www.netlib.org/clapack/CLAPACK-3.1.1/SRC/dgels.c).

**Comment by pkazanzides** [comment]
There seems to be an inconsistency in the code, according to the `dgels` documentation.  The vector `b` should be of size `ldb`, which should be >= `max(M,N)`, but the size of `b` is 3 and the other dimensions are 7. If I had to guess, I would say that the `dgels` documentation is wrong and `ldb` should be set to 3.

**Comment by pkazanzides** [comment]
Alternatively, the size of `b` could be changed to 7.

**Comment by ahundt** [comment]
I think the documentation of LAPACK is right and our implementation is buggy.

It appears the dimensions & amount of memory allocated is fairly broken, not even meeting the minimum required available memory, let alone the maximum. :-(

based on the specification for the total working memory as follows:
```

    LWORK   (input) INTEGER   
            The dimension of the array WORK.   
            LWORK >= max( 1, MN + max( MN, NRHS ) ).   
            For optimal performance,   
            LWORK >= max( 1, MN + max( MN, NRHS )*NB ).   
            where MN = min(M,N) and NB is the optimum block size.   

            If LWORK = -1, then a workspace query is assumed; the routine   
            only calculates the optimal size of the WORK array, returns   
            this value as the first entry of the WORK array, and no error   
            message related to LWORK is issued by XERBLA.   

```

I added 
```
    assert(lwork >= std::max( 1, rows*cols + std::max( rows*cols, nrhs ) ));
    // for maximum performance uncomment assert below:
    //assert(lwork >= std::max( 1, rows*cols + std::max( rows*cols, nrhs )* cols * maxmn ));
```

lwork doesn't even meet the first requirement right now. Perhaps this is partially due to me having something setup incorrectly further back, I need to investigate.

**Comment by ahundt** [comment]
Yeah, this code is definitely not allocating enough space for the lapack function

**Comment by pkazanzides** [comment]
O.K.  I see another problem.  The `dgels` documentation is rather unclear.  In the beginning, it states that `b` is size `M` (actually, `M x nrhs`, but `nrhs` is 1 for us, so I will drop it).  But, the vector `b` passed to the function also returns the solution vector, `X`, which in this case is of size `N`.  That is why `b` must be of size `max(M,N)`.

**Comment by ahundt** [comment]
In the code there are cases to allocate for ls, lsi, lsei, but not what we are using which is dgels.

**Comment by pkazanzides** [comment]
Perhaps dgels is the same as ls.  Anyway, clearly `b` must be fixed. The easiest for now is to create a new `b`, say `btmp` and pass that to dgels:
```c++
btmp = new CISSTNETLIB_DOUBLE[maxmn];
for (int i = 0; i < rows; i++)
    btmp[i] = b[i];
cisstNetlib_dgels_(..., btmp, ....)
```
i.e., pass `btmp` instead of `b.Pointer()`. If this works, there probably is a better way to do it, perhaps by using `solutionFriend.GetX()` instead of allocating a new variable `btmp`.

**Comment by ahundt** [comment]
is the number of right hand sides always 1?

**Comment by pwilken3** [comment]
We're treating B and X as vectors, so NHRS would always be one for our purposes since that is the number of columns for B and X.

**Comment by ahundt** [comment]
Ok, I've had to change a bunch of stuff but I've got it running past that point now. I'll have to figure out the process for submitting/merging those changes. Unfortunately, something is still quite quite wrong, because the result of running the constraint solver is now `NMR_MALFORMED`.

**Comment by ahundt** [comment]
I've created a [pull request with my cisstNumerical changes](https://github.com/jhu-cisst/cisst/pull/32).

Here is my [current controller implementation](https://gist.github.com/ahundt/7fdb6bec74cc2ea3d742).

Paul, I probably need your help with this one, should I be inheriting from mtsVFController or mtsVFFollow? Also, how can I make sure that ObjectiveMatrixRef has the correct dimensions?

**Comment by ahundt** [comment]
I've been able to get back to the `NMR_MALFORMED` error by hardcoding smaller dimensions to my Jacobian to exclude the rotation component, though I would like to make progress on resolving both issues.

**Comment by pwilken3** [comment]
You should be inheriting from mtsVFController, as mtsVFFollow would just be one object in a list that your controller owns. To ensure that your objective matrix and vector are set up properly within mtsVFFollow, make sure that the number of variables is set in the controller (determines columns for matrix) and that the number of "ObjectiveRows" is set properly in the mtsVFDataFollow object (rows of matrix and size of vector). 

The jacobian will most likely be a 6x7, but since the one I pushed is purely for translation, you will have to resize the jacobian to 3x7 for now. I have a version that implements both translation and rotation, so I can simply check to see how many rows were allocated (3 or 6) and fill in the references accordingly. I'll make another commit to the devel branch with this detail, but until then the jacobian resizing should be fine.

Another thing to examine is nmrConstraintOptimizer's solve method. You may reach the end with the code NMR_MALFORMED or you may be exiting early with that code. It is useful to debug and find which is happening and why.

**Comment by ahundt** [comment]
we've been able to clear these hurdles! thanks!

**Comment by pwilken3** [comment]
Thanks for the reminder, Andrew. I'm marking this specific issue as closed, since it is working with vrep at least for a simple example.
