### ISSUE TITLE
cmake assumes build directory is also the installation directory

### ISSUE THREAD

**Issue by ahundt** [jhu-saw/sawConstraintController#18]
When I run the [automated installer I created](https://github.com/ahundt/homebrew-robotics/blob/master/sawconstraintcontroller.rb) an incorrect cmake config was created. 
This appears to be due to a bug in the cmake scripts, and I expect a build folder variable is used rather than an install folder variable. The folders in which it was built are temporary and immediately deleted after the build is complete.
## Actual Output CMake Config File

``` cmake
#
# Author(s):  Paul Wilkening
# Created on: 2014-06-07
#
# (C) Copyright 2014 Johns Hopkins University (JHU), All Rights Reserved.
#

# this file is automatically generated by CMake from
# sawConstraintControllerConfig.cmake.in

set (sawConstraintController_VERSION_MAJOR "1")
set (sawConstraintController_VERSION_MINOR "0")
set (sawConstraintController_VERSION_PATCH "0")
set (sawConstraintController_VERSION "1.0.0")

set (sawConstraintController_INCLUDE_DIR "/tmp/sawconstraintcontroller20150906-76127-x5lpnv/include;/tmp/sawconstraintcontroller20150906-76127-x5lpnv/include")
set (sawConstraintController_LIBRARY_DIR "/tmp/sawconstraintcontroller20150906-76127-x5lpnv/lib")
set (sawConstraintController_LIBRARIES   "sawConstraintController")

```
## Expected File

``` cmake
#
# Author(s):  Paul Wilkening
# Created on: 2014-06-07
#
# (C) Copyright 2014 Johns Hopkins University (JHU), All Rights Reserved.
#

# this file is automatically generated by CMake from
# sawConstraintControllerConfig.cmake.in

set (sawConstraintController_VERSION_MAJOR "1")
set (sawConstraintController_VERSION_MINOR "0")
set (sawConstraintController_VERSION_PATCH "0")
set (sawConstraintController_VERSION "1.0.0")

set (sawConstraintController_INCLUDE_DIR "/usr/local/include;/usr/local/include")
set (sawConstraintController_LIBRARY_DIR "/usr/local/lib")
set (sawConstraintController_LIBRARIES   "sawConstraintController")
```

**Comment by adeguet1** [comment]
Can you use cisst_find_saw_component instead of find_package?
For example: https://github.com/jhu-dvrk/sawIntuitiveResearchKit/blob/master/examples/CMakeLists.txt#L41

**Comment by ahundt** [comment]
Will that fn be present after I call find_package( cisst)?

Could you also help me understand why a special facility is required?

I'm using a cmake library that automates stuff so calling a custom function
will mean I cannot take advantage of those tools in this case.

Thanks!


On Monday, September 28, 2015, Anton Deguet <notifications@github.com>
wrote:

> Can you use cisst_find_saw_component instead of find_package?
> For example:
> https://github.com/jhu-dvrk/sawIntuitiveResearchKit/blob/master/examples/CMakeLists.txt#L41
>
>
> > On Sep 28, 2015, at 10:20 AM, Andrew Hundt <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > When I run the automated installer I created an incorrect cmake config
> was created.
> > This appears to be due to a bug in the cmake scripts, and I expect a
> build folder variable is used rather than an install folder variable. The
> folders in which it was built are temporary and immediately deleted after
> the build is complete.
> >
> > Actual Output CMake Config File
> >
> > #
> > # Author(s): Paul Wilkening
> > # Created on: 2014-06-07
> > #
> > # (C) Copyright 2014 Johns Hopkins University (JHU), All Rights Reserved.
> > #
> >
> >
> >
> > # this file is automatically generated by CMake from
> > # sawConstraintControllerConfig.cmake.in
> >
> >
> >
> > set (sawConstraintController_VERSION_MAJOR "1"
> > )
> >
> > set (sawConstraintController_VERSION_MINOR "0"
> > )
> >
> > set (sawConstraintController_VERSION_PATCH "0"
> > )
> >
> > set (sawConstraintController_VERSION "1.0.0"
> > )
> >
> >
> > set (sawConstraintController_INCLUDE_DIR
> "/tmp/sawconstraintcontroller20150906-76127-x5lpnv/include;/tmp/sawconstraintcontroller20150906-76127-x5lpnv/include"
> > )
> >
> > set (sawConstraintController_LIBRARY_DIR
> "/tmp/sawconstraintcontroller20150906-76127-x5lpnv/lib"
> > )
> >
> > set (sawConstraintController_LIBRARIES "sawConstraintController"
> > )
> >
> > Expected File
> >
> > #
> > # Author(s): Paul Wilkening
> > # Created on: 2014-06-07
> > #
> > # (C) Copyright 2014 Johns Hopkins University (JHU), All Rights Reserved.
> > #
> >
> >
> >
> > # this file is automatically generated by CMake from
> > # sawConstraintControllerConfig.cmake.in
> >
> >
> >
> > set (sawConstraintController_VERSION_MAJOR "1"
> > )
> >
> > set (sawConstraintController_VERSION_MINOR "0"
> > )
> >
> > set (sawConstraintController_VERSION_PATCH "0"
> > )
> >
> > set (sawConstraintController_VERSION "1.0.0"
> > )
> >
> >
> > set (sawConstraintController_INCLUDE_DIR
> "/usr/local/include;/usr/local/include"
> > )
> >
> > set (sawConstraintController_LIBRARY_DIR "/usr/local/lib"
> > )
> >
> > set (sawConstraintController_LIBRARIES "sawConstraintController")
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhu-saw/sawConstraintController/issues/18#issuecomment-143770529>
> .
>


-- 

Cheers!
Andrew Hundt

**Comment by ahundt** [comment]
This issue is still outstanding and has become more urgent.

**Comment by ahundt** [comment]
@adeguet1 I've made a patch that fixes it. You will probably have to adapt it a bit so it will work with your system, since it currently makes assumptions incompatible with assumptions found in typical package build and installation. You may want to use it as a reference for future packages as well, though this one can still use improvement too.

**Comment by ahundt** [comment]
@pwilken3 I tried the latest version in devel and it currently breaks the independent cmake build configuration. 

Here are the files generated by `make install` with an independent build:
https://gist.github.com/ahundt/0bd2c3379072dbb63ba5

As you can see in [sawConstraintControllerConfig.cmake line 65](https://gist.github.com/ahundt/0bd2c3379072dbb63ba5#file-sawconstraintcontrollerconfig-cmake-L65) the include, library, and libraries dirs are set to the empty string. 

I believe the ideal way to make use of this is to use [target_include_directores](https://cmake.org/cmake/help/v3.0/command/target_include_directories.html) rather than include_directories. We could also update it to use the actual include directory variables set by the build. 

Thoughts?

**Comment by ahundt** [comment]
This is the tool we should be using for this: https://cmake.org/cmake/help/v3.0/module/CMakePackageConfigHelpers.html

**Comment by adeguet1** [comment]
This feature definitively looks good but... it requires CMake 3.  Since Ubuntu 12.04 comes with 2.6 and Ubuntu 14.04 with 2.8 this is pretty much a no-go.  Being snowed in I implemented a simplified version of this code that seems compatible with older CMake.  For now, I updated two SAW components (sawKeyboard and sawTextToSpeech).  sawTextToSpeech comes with an example that uses sawKeyboard.  I replaced the "saw_find_components" calls by a more standard find_package for the sawTextToSpeech example.  I tested on MacOS building the example along cisst/saw and against a "make install" in /usr/local.  I also tested on ROS/Catkin/Ubuntu 14.04.   Can you give it a try using whatever is your framework?  cisst is unchanged, sawKeyboard and sawTextToSpeech on branches bug-find_package.

**Comment by adeguet1** [comment]
If the code works for sawKeyboard/TextToSpeech, I plan to patch all saw components on github/cisst-saw and push to master branches (after review of course).

**Comment by ahundt** [comment]
@adeguet1 can you send a link to the commit or pull request?

**Comment by ahundt** [comment]
@adeguet1 the install instructions seem pretty simple for the current cmake version https://cmake.org/install/

**Comment by adeguet1** [comment]
@ahundt, can you try 0a3da17747983a390fded5d8d319a8ac8c711b18 in branch bug-find_package.  This has been tested in different configurations:
 * catkin ROS Hydro Ubuntu 12.04
 * catkin ROS Indigo Ubuntu 14.04
 * Mac OS build all (cisst, cisstNetlib DOWNLOAD, sawConstraintController with example) in single build tree
 * Mac OS, separate build tree for each removed build tree after install in /usr/local:
  * cisstNetlib master from git, C compile, make, make install
  * cisst master from git, turned on cisstNetlib, cisstRobot, off cisstStereoVision (faster compile)
  * sawConstraintController bug-find_package from git
  * example from sawConstraintController
I believe the last configuration reproduces what brew is doing
