### ISSUE TITLE
CMAKE sawConstraintController_INCLUDE_DIR is wrong

### ISSUE THREAD

**Issue by liushuya7** [jhu-saw/sawConstraintController#27]
The package could be successfully compiled using `colcon build` (Ubuntu 24.04 ROS2 Humble) I'm using `devel` branch.
I want to use this package in another package, I have the `CMakeLists.txt`:
```cmake
    find_package(sawConstraintController REQUIRED)
    include_directories(
        include
        ${sawConstraintController_INCLUDE_DIR}
        )
```
When I print the `${sawConstraintController_INCLUDE_DIR}`, it is `$COLCON_WS/install/sawConstraintController/share/include`. However, is should be: `$COLCON_WS/install/sawConstraintController/include` as the `install/sawConstraintController` directory is like this:
```
sawConstraintController/
├── include
│   └── sawConstraintController
├── lib
│   └── libsawConstraintController.so
└── share
    ├── colcon-core
    └── sawConstraintController
```
How to correct this to make it compile using `colcon build`?

**Comment by adeguet1** [comment]
I patched the CMake code based on other components but I don't really have a way to test this.  Can you pull the latest devel branch and check?

**Comment by liushuya7** [comment]
Awesome! I just checked -- everything works as desired! Thanks!!
