### ISSUE TITLE
Do I need a specific branch of cisst?

### ISSUE THREAD

**Issue by ahundt** [jhu-saw/sawConstraintController#3]
Do I need a specific branch of cisst to satisfy dependencies?

Is there any other specific configuration information I need?

**Comment by pwilken3** [comment]
You don't need to use a different branch, the latest version of master should be fine. Make sure you are building what is specified in REQUIRED_CISST_LIBRARIES (cisstCommon, cisstVector, cisstOSAbstraction, cisstMultiTask, cisstParameterTypes, cisstRobot, and cisstNumerical). That should be everything you need.

**Comment by pwilken3** [comment]
I have added these details to the wiki page and I've helped Andrew get this component running.
